In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.14.0'

In [3]:
x = np.arange(10).reshape(-1, 1).astype('float32')

In [4]:
x_ph = tf.placeholder(x.dtype, x.shape)
train_dataset = tf.data.Dataset.from_tensor_slices(x_ph).batch(4, drop_remainder=True).repeat()

iterator = train_dataset.make_initializable_iterator()
next_element = iterator.get_next()

W1212 12:05:35.933345 10836 deprecation.py:323] From <ipython-input-4-8a14886c4283>:4: DatasetV1.make_initializable_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_initializable_iterator(dataset)`.


In [5]:
def make_model():
    inputs = tf.keras.Input(shape=(1,))
    outputs = inputs + 1
    model = tf.keras.Model(inputs, outputs)
    return model

In [6]:
model = make_model()

In [7]:
out1 = model(next_element)
out2 = model(model.input)

In [8]:
with tf.Session() as sess:
    sess.run(iterator.initializer, feed_dict={x_ph: x})
    for i in range(20):
        print(sess.run(out1))
        print(sess.run(out2, feed_dict={model.input: np.ones((4,1))}))
        print('-----')

[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[1.]
 [2.]
 [3.]
 [4.]]
[[2.]
 [2.]
 [2.]
 [2.]]
-----
[[5.]
 [6.]
 [7.]
 [8.]]
[[2.]
 [2.]
 [2.]
 [2.]