In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Layer, Input

print(tf.__version__)

2.0.0


In [2]:
class CustomDropout(Layer):
    def __init__(self, rate, autocast=False, **kwargs):
        super(CustomDropout, self).__init__(autocast=False, **kwargs)
        self.rate = rate
        
    def call(self, inputs, training=None):
        if training:
            return tf.nn.dropout(inputs, rate=self.rate)
        return inputs

In [3]:
class CustomLayer(Layer):
    def __init__(self, autocast=False, **kwargs):
        super(CustomLayer, self).__init__(autocast=False, **kwargs)
        
    def call(self, inputs, training=None):
        if training:
            return 1
        else:
            return 0

In [4]:
inputs = Input(shape=(10,))
outputs = CustomLayer()(inputs)

model = Model(inputs, outputs)

x = np.ones((1,10))

print('Default behavior: ', model(x))
print('Training = True: ', model(x, training=True))
print('Training = False: ', model(x, training=False))

Default behavior:  0
Training = True:  1
Training = False:  0


In [5]:
outputs2 = CustomDropout(rate=0.9)(inputs)

model2 = Model(inputs, outputs2)

print('Default behavior: ', model2(x))
print('Training = True: ', model2(x, training=True))
print('Training = False: ', model2(x, training=False))

W1123 14:31:15.003648 14564 nn_ops.py:4283] Large dropout rate: 0.9 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.
W1123 14:31:15.025561 14564 nn_ops.py:4283] Large dropout rate: 0.9 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.


Default behavior:  tf.Tensor([[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(1, 10), dtype=float64)
Training = True:  tf.Tensor([[ 0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]], shape=(1, 10), dtype=float64)
Training = False:  tf.Tensor([[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(1, 10), dtype=float64)
