In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth',
                    'PetalLength', 'PetalWidth', 'Species']
train = pd.read_csv('data/iris_training.csv', names=CSV_COLUMN_NAMES, header=0)
train_x, train_y = train, train.pop('Species')

In [3]:
# Feature columns describe how to use the input.
feature_columns = []
for key in train_x.keys():
    feature_columns.append(tf.feature_column.numeric_column(key=key))

In [4]:
dataset = tf.data.Dataset.from_tensor_slices((dict(train_x), train_y))
dataset = dataset.batch(5)

In [5]:
iterator = dataset.make_one_shot_iterator()

In [6]:
next_element = iterator.get_next()

In [7]:
feature, label = next_element

In [8]:
feature

{'SepalLength': <tf.Tensor 'IteratorGetNext:2' shape=(?,) dtype=float64>,
 'SepalWidth': <tf.Tensor 'IteratorGetNext:3' shape=(?,) dtype=float64>,
 'PetalLength': <tf.Tensor 'IteratorGetNext:0' shape=(?,) dtype=float64>,
 'PetalWidth': <tf.Tensor 'IteratorGetNext:1' shape=(?,) dtype=float64>}

In [9]:
label

<tf.Tensor 'IteratorGetNext:4' shape=(?,) dtype=int64>

In [10]:
inputs = tf.feature_column.input_layer(feature, feature_columns)

In [11]:
inputs

<tf.Tensor 'input_layer/concat:0' shape=(?, 4) dtype=float32>

In [16]:
with tf.Session() as sess:
    result = sess.run([inputs, next_element])
    print(result[0])
    print(result[1])

[[5.6 2.2 6.4 2.8]
 [3.3 1.  5.  2.3]
 [4.5 1.7 4.9 2.5]
 [1.5 0.1 4.9 3.1]
 [1.7 0.3 5.7 3.8]]
({'SepalLength': array([6.4, 5. , 4.9, 4.9, 5.7]), 'SepalWidth': array([2.8, 2.3, 2.5, 3.1, 3.8]), 'PetalLength': array([5.6, 3.3, 4.5, 1.5, 1.7]), 'PetalWidth': array([2.2, 1. , 1.7, 0.1, 0.3])}, array([2, 1, 2, 0, 0], dtype=int64))
